dist: trusty
language: go
go:
- "1.10"

install:
- go get github.com/mitchellh/gox
- go get -t ./...

script:
- go install ./...
- gox -output="bin/{{.OS}}_{{.Arch}}/{{.Dir}}" ./...

before_deploy:
- export VERSION=`npmrc version`
- for i in bin/*; do tar -zvcf "$i.tar.gz" "$i"; done

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*.tar.gz
  skip_cleanup: true
  name: npmrc $VERSION
  body: "https://github.com/RecuencoJones/npmrc#install"
  on:
    tags: true

after_deploy:
- echo "Brew hash: $(shasum -a 256 ./bin/darwin_amd64.tar.gz | awk '{ print $1 }')"
