dist: trusty
language: go
go:
- "1.10"

install:
- go get github.com/mitchellh/gox
- go get -t ./...

script:
- go install ./...
- gox -output="bin/{{.Dir}}_{{.OS}}_{{.Arch}}" ./...

before_deploy:
- export VERSION=`npmrc version`

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/**/*
  skip_cleanup: true
  name: npmrc $VERSION
  on:
    tags: true
