dist: trusty
language: go
go:
- "1.10"

install:
- make setup

script:
- make build

before_deploy:
- make install
- make x-compile
- export VERSION=`npmrc version`

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*.tar.gz
  skip_cleanup: true
  name: npmrc $VERSION
  body: "https://github.com/RecuencoJones/npmrc#install"
  on:
    tags: true

after_deploy:
- echo "Brew hash: $(shasum -a 256 ./bin/darwin_amd64.tar.gz | awk '{ print $1 }')"
